/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
export type { BorrowedBookResponse } from './models/borrowed-book-response';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedBackResponse } from './models/feed-back-response';
export type { PageResponsesBookResponse } from './models/page-responses-book-response';
export type { PageResponsesBorrowedBookResponse } from './models/page-responses-borrowed-book-response';
export type { PageResponsesFeedBackResponse } from './models/page-responses-feed-back-response';
export type { RegistrationRequest } from './models/registration-request';
